// modules/angular-store/projects/store-test/src/app/features/tutorial/tutorialList.ts
import { REMOVE_TUTORIAL } from '../../store/actions';
import { Store } from 'ajwah-angular-store';
import { Component, ChangeDetectionStrategy, Input } from '@angular/core';


@Component({
    selector: 'tutorialList',
    template: `
    <ul class="list-group" >
        <li class="list-group-item active">Tutorials</li>
        <li *ngFor="let t of tutorials"  class="list-group-item">{{t.name}} <span class="del" (click)="onRemove(t.name)">x</span></li>
    </ul>
    <counter [counter]="counter"></counter>
    `,
    changeDetection: ChangeDetectionStrategy.OnPush
})
export class TutorialList {
    @Input() tutorials: any[];
    @Input() counter: any[];
    constructor(public store: Store) {

    }

    onRemove(name) {
        this.store.dispatch({ type: REMOVE_TUTORIAL, payload: name });
    }
}

// examples/vue-app/src/components/TutorialList.vue
<template>
  <div class="list-group">
    <a href="#" class="list-group-item list-group-item-action active">Tutorials</a>
    <a
      v-for="t in tutorial.data"
      href="#"
      class="list-group-item list-group-item-action"
      @click="onRemove(t.name)"
      v-bind:key="t.name"
    >{{t.name}}</a>
  </div>
</template>

<script>
import { REMOVE_TUTORIAL } from "../states/actions";
export default {
  name: "TutorialList",
  subscriptions() {
    return {
      tutorial: this.store.select("tutorial")
    };
  },
  methods: {
    onRemove(name) {
      this.store.dispatch({ type: REMOVE_TUTORIAL, payload: name });
    }
  }
};
</script>
