// examples/vue-app/src/components/AddTutorial.vue
<template>
  <form @submit="addTutorial($event)">
    <div class="form-group">
      <label for="name">Tutorial Name</label>
      <input
        v-model="tutorialModel.name"
        type="text"
        class="form-control"
        id="name"
        name="name"
        placeholder="Enter Name"
      >
    </div>
    <div class="form-group">
      <label for="url">URL</label>
      <input
        v-model="tutorialModel.url"
        type="text"
        class="form-control"
        id="url"
        name="url"
        placeholder="Enter url"
      >
    </div>
    <button type="submit" class="btn btn-primary">Submit</button>
  </form>
</template>
<script>
import { ADD_TUTORIAL } from "../states/actions";
export default {
  name: "AddTutorial",
  data() {
    return {
      tutorialModel: { name: "", url: "" }
    };
  },
  methods: {
    addTutorial(e) {
      e.preventDefault();
      this.store.dispatch({
        type: ADD_TUTORIAL,
        payload: { ...this.tutorialModel }
      });
      this.tutorialModel = { name: "", url: "" };
    }
  }
};
</script>

// modules/angular-store/projects/store-test/src/app/components/addTutorial.ts
import { ADD_TUTORIAL } from '../store/actions';
import { Store } from 'ajwah-angular-store';
import { Component, ChangeDetectionStrategy } from '@angular/core';


@Component({
    selector: 'addTutorial',
    template: `
    <form (submit)="addTutorial($event)">
        <input [(ngModel)]="tutorialModel.name" type="text" name="name" placeholder="Enter Name" />
        <input [(ngModel)]="tutorialModel.url" type="text" name="url" placeholder="Enter url" />
        <button type="submit" class="btn">Add Tutorial</button>
    </form>`,
    changeDetection: ChangeDetectionStrategy.OnPush
})
export class AddTutorial {
    tutorialModel = { name: '', url: '' };
    constructor(public store: Store) {

    }

    addTutorial(e) {
        e.preventDefault();
        this.store.dispatch({ type: ADD_TUTORIAL, payload: { ...this.tutorialModel } });
        this.tutorialModel.name = '';
        this.tutorialModel.url = '';
    }
}
