// examples/vue-app/src/components/AddTutorial.vue
<template>
  <form @submit="addTutorial($event)">
    <div class="form-group">
      <label for="name">Tutorial Name</label>
      <input
        v-model="tutorialModel.name"
        type="text"
        class="form-control"
        id="name"
        name="name"
        placeholder="Enter Name"
      >
    </div>
    <div class="form-group">
      <label for="url">URL</label>
      <input
        v-model="tutorialModel.url"
        type="text"
        class="form-control"
        id="url"
        name="url"
        placeholder="Enter url"
      >
    </div>
    <button type="submit" class="btn btn-primary">Submit</button>
  </form>
</template>
<script>
import { ADD_TUTORIAL } from "../states/actions";
export default {
  name: "AddTutorial",
  data() {
    return {
      tutorialModel: { name: "", url: "" }
    };
  },
  methods: {
    addTutorial(e) {
      e.preventDefault();
      this.store.dispatch({
        type: ADD_TUTORIAL,
        payload: { ...this.tutorialModel }
      });
      this.tutorialModel = { name: "", url: "" };
    }
  }
};
</script>

// examples/react-app/src/components/addTutorialComponent.js
import React, { PureComponent } from 'react';
import { ADD_TUTORIAL } from "../states/actions";
import { getStore } from 'ajwah-react-store';


class AddTutorial extends PureComponent {
    onSubmit = event => {
        event.preventDefault();
        const el = event.target.elements;
        const model = { name: el.name.value, url: el.url.value }
        getStore().dispatch({ type: ADD_TUTORIAL, payload: model });
    }
    render() {
        console.log('add-tutorial-component')
        return <form onSubmit={this.onSubmit}>
            <div className="form-group">
                <label htmlFor="name">Tutorial Name</label>
                <input type="text" className="form-control" id="name" name="name" aria-describedby="emailHelp" placeholder="Enter Name" />
            </div>
            <div className="form-group">
                <label htmlFor="url">URL</label>
                <input type="text" className="form-control" id="url" name="url" aria-describedby="emailHelp" placeholder="Enter url" />
            </div>
            <button type="submit" className="btn btn-primary">Submit</button>
        </form>
    }
}
export default AddTutorial;
