// modules/angular-store/projects/store-test/src/app/components/addTodo.ts
import { ADD_TODO } from '../store/actions';
import { Store } from 'ajwah-angular-store';
import { Component, ChangeDetectionStrategy } from '@angular/core';


@Component({
    selector: 'addTodo',
    template: `
    <form (submit)="addTodo($event)">
        <input type="text" [(ngModel)]="title" name="title" placeholder="Add Todo..." />
        <input type="submit" value="Submit" class="btn" />
    </form>`,
    changeDetection: ChangeDetectionStrategy.OnPush
})
export class AddTodoComponent {
    title: string;
    constructor(public store: Store) {

    }

    addTodo(e) {
        e.preventDefault();
        const newTodo = {
            title: this.title,
            completed: false
        }
        this.store.dispatch({ type: ADD_TODO, payload: newTodo });
        this.title = '';
    }
}

// examples/react-app/src/components/AddTodo.js
import React from 'react';
import { store } from "ajwah-store";
import { ADD_TODO } from '../states/actions'

function addItem(e) {
  e.preventDefault();
  const newTodo = {
    title: e.target.elements.title.value,
    completed: false
  }
  store().dispatch({ type: ADD_TODO, payload: newTodo });
  e.target.elements.title.value = '';
}

function addTodo(props) {
  return <div>
    <form onSubmit={addItem}>
      <input type="text" name="title" placeholder="Add Todo..." />
      <input type="submit" value="Submit" className="btn" />
    </form>
  </div>

}
export default addTodo;
