// examples/vue-app-ts/src/components/Counter.vue
<template>
  <p>
    <button class="btn" @click="inc()">+</button>
    <button class="btn" @click="dec()">-</button>
    <button class="btn" @click="async_inc()">async(+)</button>
    {{counter.msg||counter.count}}
  </p>
</template>

<script>
import { INCREMENT, DECREMENT, ASYNC_INCREMENT } from "../states/actions";
import { dispatch } from "ajwah-store";

export default {
  name: "Counter",
  subscriptions() {
    return {
      counter: this.store.select("counter")
    };
  },

  methods: {
    inc() {
      //this.store.dispatch({ type: INCREMENT });
      dispatch(INCREMENT);
    },
    dec() {
      this.store.dispatch({ type: DECREMENT });
    },
    async_inc() {
      this.store.dispatch({ type: ASYNC_INCREMENT });
    }
  }
};
</script>

// examples/react-app/src/components/counterComponent.js
import React, { PureComponent } from 'react';
import { INCREMENT, DECREMENT, ASYNC_INCREMENT } from "../states/actions";

import { Connect } from 'ajwah-store';


@Connect()
class Counter extends PureComponent {

    increment = () => {
        this.store.dispatch({ type: INCREMENT });
    }
    decrement = () => {
        this.store.dispatch({ type: DECREMENT });
    }
    asyncIncrement = () => {
        this.store.dispatch({ type: ASYNC_INCREMENT });
    }
    render() {
        const { counter } = this.props;
        console.log('counter-component');
        return <span>
            <button className="btn" onClick={this.increment}>+</button>
            <button className="btn" onClick={this.decrement}>-</button>
            <button className="btn" onClick={this.asyncIncrement}>Asunc (+)</button> <b>count {counter.msg || counter.count}</b>
        </span>
    }
}
export default Counter;
