// examples/my-app/src/app/components/todos/loading/loading.component.ts
import { TodosController } from './../controllers/todos-controller';
import { Component, OnInit } from '@angular/core';

@Component({
  selector: 'app-loading',
  templateUrl: './loading.component.html',
  styleUrls: ['./loading.component.css']
})
export class LoadingComponent implements OnInit {
  
  constructor(public service: TodosController) { }
  
  rotate$=this.service.rotate$;

  ngOnInit(): void {
  }

}

<div style="position: absolute;left: 50%;top:100" *ngIf="rotate$|async as r">
	<svg width="70" height="70" [ngStyle]="{transform:'rotate('+r+'deg)'}">
		<circle cy="35" cx="35" r="35" fill="lightgrey"></circle>
		<circle cy="15" cx="35" r="10" fill="black"></circle>
	</svg>
</div>

// examples/react-app/src/components/loading.tsx
import React from 'react';
import { useStream } from '../states/useStream';
import { rotate$ } from '../services/todoService';

export default () => {
    const rotate = useStream(rotate$, 0);
    return <div style={{ position: 'relative' }}>
        <div style={{ position: 'absolute', left: '50%', top: 0 }}>
            {rotate > 0 ? <svg
                width="70"
                height="70"
                style={{ transform: `rotate(${rotate}deg)` }}
            >
                <circle cy="35" cx="35" r="35" fill="lightgrey"></circle>
                <circle cy="15" cx="35" r="10" fill="black"></circle>
            </svg> : null}
        </div>
    </div>
}
