// examples/ngApp/src/app/features/todo/todo-item/todo-item.component.ts
import { Store } from 'ajwah-angular-store';
import { REMOVE_TODO, UPDATE_TODO } from '../../../store/actions';
import { Component, ChangeDetectionStrategy, Input } from '@angular/core';

@Component({
  selector: 'mac-todoItem',
  templateUrl: './todo-item.component.html',
  changeDetection: ChangeDetectionStrategy.OnPush
})
export class TodoItemComponent {
  title: string;
  @Input() todo: any;
  constructor(public store: Store) {

  }

  updateTodo(e) {
    this.todo.completed = e.target.checked;
    this.store.dispatch({ type: UPDATE_TODO, payload: this.todo })
  }

  removeTodo() {
    this.store.dispatch({ type: REMOVE_TODO, payload: this.todo })
  }
}
<div class="todo-item" [ngClass]="{'is-complete':todo.completed}">
  <p>
    <input [checked]="todo.completed" type="checkbox" (change)="updateTodo($event)" />
    <span class="item-text">{{todo.title}}</span>
    <button (click)="removeTodo()" class="del">x</button>
  </p>
</div>

// examples/react-app/src/components/TodoItem.js
import React from 'react';
import { dispatch } from "ajwah-store";
import { REMOVE_TODO, UPDATE_TODO } from '../states/actions'

function updateTodo(todo, e) {
  todo.completed = e.target.checked;
  dispatch({ type: UPDATE_TODO, payload: todo })
}

function removeTodo(todo) {

  dispatch(REMOVE_TODO, todo)
}

function todoItem(props) {
  const { todo } = props;
  return <div className={`todo-item ${todo.completed || 'is-complete'}`} >
    <p>
      <input checked={todo.completed} type="checkbox" onChange={(e) => updateTodo(todo, e)} />
      <span className="item-text">{todo.title}</span>
      <button onClick={() => removeTodo(todo)} className="del">x</button>
    </p>
  </div>
}

export default todoItem;
