// examples/vue3App/src/components/todos.vue
<template>
  <div class="bg-white rounded shadow p-6 m-4 w-full lg:w-3/4 lg:max-w-lg">
    <loading />
    <addTodo />
    <toolBar />
    <todoItem
      v-for="todo in todos"
      :key="todo.id"
      v-bind:todo="todo"
    ></todoItem>
  </div>
</template>

<script>
import addTodo from "./addTodo.vue";
import todoItem from "./todoItem.vue";
import loading from "./loading.vue";
import toolBar from "./toolBar.vue";
import "../states/todoState";
import { todos$, TodoActions } from "../services/todoService";
import { useStream } from "../states/useStream";
import store from "../states/store";

export default {
  name: "todos",
  components: {
    addTodo,
    todoItem,
    loading,
    toolBar,
  },
  setup() {
    store.dispatch(TodoActions.loadtodos);
    const todos = useStream(todos$, []);
    return { todos };
  },
};
</script>

<style>
</style>

// examples/react-app/src/components/todos.tsx
import React from 'react';
import Loading from './loading';
import AddTodo from './addTodo';
import Toolbar from './toolbar';
import TodoItem from './todoItem';
import '../states/todoState';
import { useStream } from '../states/useStream';
import { todos$ } from '../services/todoService';
import store from '../states/store';
import { TodoActions } from '../models/todo';

store.dispatch(TodoActions.loadtodos);

export default () => {
    const todos = useStream(todos$, []);
    return <div className="bg-white rounded shadow p-6 m-4">
        <Loading></Loading>
        <AddTodo></AddTodo>
        <Toolbar></Toolbar>
        {todos.map(todo => <TodoItem todo={todo} key={todo.id}></TodoItem>)}
    </div>
}
