// examples/react-app/src/todo/components/loading.tsx
import React, { FC } from "react";
import { StreamBuilder, Get } from 'ajwah-reactive-form';
import { TodoStateController } from "../services/todoStateController";


const loading = () => <StreamBuilder
  //initialData={0}
  stream={Get(TodoStateController).rotate$}
  render={({ data }) =>
    <div style={{ position: "relative" }}>
      <div style={{ position: "absolute", left: "50%", top: 0 }}>
        {data > 0 ?
          <svg
            width="70"
            height="70"
            style={{ transform: `rotate(${data}deg)` }}
          >
            <circle cy="35" cx="35" r="35" fill="lightgrey" />
            <circle cy="15" cx="35" r="10" fill="black" />
          </svg> : null
        }
      </div>
    </div>
  } />

export default loading;

// examples/vue3App/src/components/loading.vue
<template>
  <div style="position: relative">
    <div style="position: absolute; left: 50%; top: 0" v-show="rotate > 0">
      <svg
        width="70"
        height="70"
        v-bind:style="{ transform: `rotate(${rotate}deg)` }"
      >
        <circle cy="35" cx="35" r="35" fill="lightgrey"></circle>
        <circle cy="15" cx="35" r="10" fill="black"></circle>
      </svg>
    </div>
  </div>
</template>

<script>
import { rotate$ } from "../services/todoService";
import { useStream } from "../states/useStream";
export default {
  name: "loading",
  setup() {
    const rotate = useStream(rotate$, 0);
    return { rotate };
  },
};
</script>

<style>
</style>
