// examples/react-apps/src/App.js
import React, { Component } from "react";
import Counter from "./components/Counter";
import Export from "./components/Export";
import StateOnDemand from "./components/StateOnDemand";
import "./index.css";
import { devTools } from "ajwah-devtools";
import store from "./states/storeService";
import registerCounterState from "./states/counterState";
registerCounterState();
devTools({ store, name: "Hi devtools" });
function App() {
  return (
    <div>
      <StateOnDemand />
      <Counter />
      <p>Export State</p>
      <Export />
    </div>
  );
}

export default App;

// examples/vue3App/src/App.vue
<template>
  <Counter />
  <todos />
</template>

<script>
import store from "./states/store";
import { devTools } from "ajwah-devtools";
import Counter from "./components/counter.vue";
import todos from "./components/todos.vue";
devTools({ store, name: "Hi tools" });
export default {
  name: "App",
  components: {
    Counter,
    todos,
  },
};
</script>
