// examples/vue3App/src/components/counter.vue
<template>
  <p>
    <button class="btn" @click="inc()">+</button>
    <button class="btn" @click="dec()">-</button>
    <button class="btn" @click="async_inc()">async(+)</button>
    {{ counter.msg || counter.count }}
  </p>
</template>

<script>
import store from "../states/store";
import "../states/counterState";
import { useStreamByStateName } from "../states/useStream";

export default {
  name: "Counter",
  setup() {
    const counter = useStreamByStateName("counter");

    function inc() {
      store.dispatch("inc");
    }
    function dec() {
      store.dispatch("dec");
    }
    function async_inc() {
      store.dispatch("asyncInc");
    }

    return { inc, dec, async_inc, counter };
  },
};
</script>

// examples/react-apps/src/components/Counter.js
import React from 'react';
import store from '../states/storeService';
import {useStreamBySelect} from 'react-ajwah';

export default () =>{
  const { counter} = useStreamBySelect({counter: store.select('counter')})

    return (
      <div>
        {counter && <div>
          <button onClick={() => store.dispatch("Inc")}>+</button>
          <button onClick={() => store.dispatch("Dec")}>-</button>
          <button onClick={() => store.dispatch("AsyncInc")}>async(+)</button>
          <span>{counter.msg || counter.count}</span>
        </div>}
      </div>
    );
}
