// modules/angular-store/projects/store-test/src/app/components/counter.ts
import { INCREMENT, DECREMENT, ASYNC_INCREMENT } from '../store/actions';
import { Store } from 'ajwah-angular-store';
import { Component, ChangeDetectionStrategy, Input } from '@angular/core';


@Component({
    selector: 'counter',
    template: `
    <p *ngIf="counter">
        <button class="btn" (click)="inc()">+</button>
        <button class="btn" (click)="dec()">-</button>
        <button class="btn" (click)="asyncInc()">async(+)</button>
        {{counter.msg||counter.count}}
    </p>`,
    changeDetection: ChangeDetectionStrategy.OnPush
})
export class Counter {

    @Input() counter: any;

    constructor(public store: Store) {
    }

    inc() {
        this.store.dispatch({ type: INCREMENT });
    }
    dec() {
        this.store.dispatch({ type: DECREMENT });
    }
    asyncInc() {
        this.store.dispatch({ type: ASYNC_INCREMENT });
    }

}

// examples/vue-app-ts/src/components/Counter.vue
<template>
  <p>
    <button class="btn" @click="inc()">+</button>
    <button class="btn" @click="dec()">-</button>
    <button class="btn" @click="async_inc()">async(+)</button>
    {{counter.msg||counter.count}}
  </p>
</template>

<script>
import { INCREMENT, DECREMENT, ASYNC_INCREMENT } from "../states/actions";
import { dispatch } from "ajwah-store";

export default {
  name: "Counter",
  subscriptions() {
    return {
      counter: this.store.select("counter")
    };
  },

  methods: {
    inc() {
      //this.store.dispatch({ type: INCREMENT });
      dispatch(INCREMENT);
    },
    dec() {
      this.store.dispatch({ type: DECREMENT });
    },
    async_inc() {
      this.store.dispatch({ type: ASYNC_INCREMENT });
    }
  }
};
</script>
