// examples/my-app/src/app/components/todos/toolbar/toolbar.component.ts
import { TodosController } from './../controllers/todos-controller';
import { Component, OnInit } from '@angular/core';

@Component({
  selector: 'app-toolbar',
  templateUrl: './toolbar.component.html',
  styleUrls: ['./toolbar.component.css']
})
export class ToolbarComponent implements OnInit {

  constructor(public controller: TodosController) { }

  ngOnInit(): void {
  }

}

<div  *ngIf="controller.searchCategory$|async as sc">
    <div class="float-left">{{controller.activeItem$|async}}</div>
    <div class="float-right">
        <button class="mr-2 text-blue-500 hover:text-blue-800" [class.active]="sc===1" (click)="controller.all()">All</button>
        <button class="mr-2 text-blue-500 hover:text-blue-800" [class.active]="sc===2" (click)="controller.active()">Active</button>
        <button class="mr-2 text-blue-500 hover:text-blue-800" [class.active]="sc===3" (click)="controller.completed()">Completed</button>
    </div>
    <div class="clear-both"></div>
</div>

// examples/react-app/src/todo/components/toolbar.tsx
import React, { FC } from 'react';

import { dispatch } from 'ajwah-reactive-form';
import { SearchCategory } from '../models/todo';
export interface Props {
    activeItem: string,
    sc?: number
}


function btnClasses(isActive: boolean) {
    return `mr-2 text-blue-500 hover:text-blue-800 ${isActive ? 'active' : ''}`
}
function filter(category: SearchCategory) {
    dispatch('searchCategory', category)
}
const toolbar: FC<Props> = ({ activeItem, sc }) =>

    <div>
        <div className="float-left">{activeItem}</div>
        <div className="float-right">
            <button
                className={btnClasses(sc == 1)}
                onClick={() => filter(SearchCategory.all)}>All</button>
            <button
                className={btnClasses(sc == 2)}
                onClick={() => filter(SearchCategory.active)}>Active</button>

            <button
                className={btnClasses(sc == 3)}
                onClick={() => filter(SearchCategory.completed)}>Completed</button>
        </div>
        <div className="clear-both"></div>

    </div>

export default toolbar;
