// examples/vue3App/src/components/todoItem.vue
<template>
  <div class="flex bg-white border p-2 justify-between">
    <div>
      <input
        class="align-middle mr-1"
        type="checkbox"
        v-model="todo.completed"
        @change="updateTodo()"
      />
      <span
        style="cursor: pointer"
        @dblclick="isDblclick = true"
        v-if="!isDblclick"
      >
        {{ todo?.description }}
      </span>
      <form v-else class="inline-block" @submit.prevent="updateTodo()">
        <input
          class="ml-1 pl-2 border"
          @blur="isDblclick = false"
          autofocus
          type="text"
          name="description"
          v-model="todo.description"
        />
      </form>
    </div>
    <div>
      <button class="text-red-200 hover:text-red-600" @click="removeTodo()">
        Remove
      </button>
    </div>
  </div>
</template>

<script>
import { ref, watch } from "vue";
import store from "../states/store";
import { TodoActions } from "../services/todoService";
import { useStream } from "../states/useStream";

export default {
  name: "todoItem",
  props: {
    todo: Object,
  },
  setup() {
    let isDblclick = ref(false);
    const updated = useStream(store.actions.whereType(TodoActions.updateEnd));
    watch(
      () => updated.value,
      (nv, ov) => {
        console.log(nv.value);
        isDblclick.value = false;
      }
    );
    function removeTodo() {
      store.dispatch(TodoActions.removeTodo, this.todo.id);
    }
    function updateTodo() {
      store.dispatch(TodoActions.updateTodo, this.todo);
    }

    return { removeTodo, updateTodo, isDblclick };
  },
};
</script>

<style>
</style>

// examples/react-my-app/src/todo/components/todoItem.tsx
import React from 'react';
import { RxForm, Field, StateObserver, dispatch, required } from 'ajwah-reactive-form';
import { Todo } from '../models/todo';
import { TodoStateController } from "../services/todoStateController";
import { delay, take } from 'rxjs/operators';



export interface Props {
    todo: Todo,
    controller: TodoStateController
}

const todoItem: React.FC<Props> = ({ controller, todo }) => {
    console.log('todoItem:')
    function submit(form: any, observer?: StateObserver) {
        dispatch('updateTodo', { ...form });
        controller.updated$.pipe(take(1)).subscribe(res => {
            observer?.notify('description', { flag: false })
        })
    }
    return <div className="flex bg-white border p-2 justify-between">
        <div>
            <input
                className="align-middle mr-1"
                type="checkbox"
                defaultChecked={todo.completed}
                onChange={(e) => dispatch('updateTodo', { ...todo, completed: e.target.checked })}
            />
            <RxForm initialValues={todo} onSubmit={submit} render={({ observer, handleSubmit }) =>
                <form className="inline-block" onSubmit={handleSubmit}>
                    <Field
                        name="description"
                        observer={observer}
                        onChange={({ elm, value }) => console.log(value, elm)}
                        autoFocus
                        validators={[required('Task should not be empty')]}
                        render={({ value, setValue, setRef, flag, setFlag }) =>

                            flag ?
                                <input
                                    className="ml-1 pl-2 border"
                                    onBlur={() => setFlag(false)}
                                    defaultValue={value}
                                    onChange={e => setValue(e.currentTarget.value)}
                                    type="text"
                                    ref={setRef}

                                />
                                :
                                <span
                                    style={{ cursor: 'pointer' }}
                                    onDoubleClick={() => setFlag(true)}
                                >
                                    {todo.description}
                                </span>
                        } />
                </form>
            } />
        </div>
        <div>
            <button
                className="text-red-200 hover:text-red-600"
                onClick={() => dispatch('removeTodo', todo)}>
                Remove
      </button>
        </div>
    </div>
}
export default React.memo(todoItem);
